apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazogbnVsbAo=
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: k8s-devstack01-cloud-config
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: k8s-devstack01-md-0
  namespace: default
spec:
  template:
    spec:
      files: []
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: k8s-devstack01
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: k8s-devstack01-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: OpenStackCluster
    name: k8s-devstack01
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: k8s-devstack01-md-0
  namespace: default
spec:
  clusterName: k8s-devstack01
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: k8s-devstack01-md-0
      clusterName: k8s-devstack01
      failureDomain: nova
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: OpenStackMachineTemplate
        name: k8s-devstack01-md-0
      version: v1.35.3
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: k8s-devstack01-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
        - name: cloud-provider
          value: external
      proxy:
        disabled: true
    files: []
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiGroup: infrastructure.cluster.x-k8s.io
      kind: OpenStackMachineTemplate
      name: k8s-devstack01-control-plane
  replicas: 3
  version: v1.35.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: k8s-devstack01
  namespace: default
spec:
  apiServerLoadBalancer:
    enabled: true
  externalNetwork:
    id: asdf
  identityRef:
    cloudName: openstack
    name: k8s-devstack01-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Cilium VXLAN overlay (udp/8472)
      direction: ingress
      etherType: IPv4
      name: Cilium VXLAN
      portRangeMax: 8472
      portRangeMin: 8472
      protocol: udp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Cilium health checks (ICMP)
      direction: ingress
      etherType: IPv4
      name: Cilium health ICMP
      protocol: icmp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Cilium health checks (tcp/4240)
      direction: ingress
      etherType: IPv4
      name: Cilium health TCP
      portRangeMax: 4240
      portRangeMin: 4240
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 1.1.1.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: k8s-devstack01-control-plane
  namespace: default
spec:
  template:
    spec:
      flavor: m1.medium
      image:
        filter:
          name: ubuntu-2404-kube-v1.35.3
      sshKeyName: k8s-devstack01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: k8s-devstack01-md-0
  namespace: default
spec:
  template:
    spec:
      flavor: m1.medium
      image:
        filter:
          name: ubuntu-2404-kube-v1.35.3
      sshKeyName: k8s-devstack01
