---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: k8s-devstack01
spec: {}
status: {}
---
apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwczovLzE5Mi4xNjguMTEuMTI4L2lkZW50aXR5CiAgICAgIHVzZXJuYW1lOiAiYWRtaW4iCiAgICAgIHByb2plY3RfaWQ6IDY1N2U3NjM5YjA3YTQ4ZDQ5NDUyMmNhYmI4NjYzYTM4CiAgICAgIHByb2plY3RfbmFtZTogImFkbWluIgogICAgICB1c2VyX2RvbWFpbl9uYW1lOiAiRGVmYXVsdCIKICAgIHJlZ2lvbl9uYW1lOiAiUmVnaW9uT25lIgogICAgaW50ZXJmYWNlOiAicHVibGljIgogICAgaWRlbnRpdHlfYXBpX3ZlcnNpb246IDMK
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: k8s-devstack01-cloud-config
  namespace: k8s-devstack01
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: k8s-devstack01-md-0
  namespace: k8s-devstack01
spec:
  template:
    spec:
      files: []
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: k8s-devstack01
  namespace: k8s-devstack01
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.199.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: k8s-devstack01-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: k8s-devstack01
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: k8s-devstack01-md-0
  namespace: k8s-devstack01
spec:
  clusterName: k8s-devstack01
  replicas: 0
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: k8s-devstack01-md-0
      clusterName: k8s-devstack01
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: k8s-devstack01-md-0
      version: v1.31.4
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: k8s-devstack01-control-plane
  namespace: k8s-devstack01
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files: []
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: k8s-devstack01-control-plane
  replicas: 1
  version: v1.31.4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: k8s-devstack01
  namespace: k8s-devstack01
spec:
  apiServerLoadBalancer:
    enabled: true
  externalNetwork:
    id: 395cd45b-81b5-4a27-a837-f1b916095d84
  identityRef:
    cloudName: openstack
    name: k8s-devstack01-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 1.1.1.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: k8s-devstack01-control-plane
  namespace: k8s-devstack01
spec:
  template:
    spec:
      flavor: m1.small
      image:
        filter:
          name: ubuntu-2204-kube-v1.31.4
      sshKeyName: k8s-devstack01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: k8s-devstack01-md-0
  namespace: k8s-devstack01
spec:
  template:
    spec:
      flavor: m1.small
      image:
        filter:
          name: ubuntu-2204-kube-v1.31.4
      sshKeyName: k8s-devstack01

