apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cni-migration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/mikejoh/capi-capo-devstack
    targetRevision: HEAD
    path: argocd/cni-migration
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
    - ServerSideApply=true
